# Generated by Django 5.2.7 on 2026-03-19 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CMS', '0001_initial'),
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='CMS.quizattempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selectedOptions',
            field=models.ManyToManyField(blank=True, to='CMS.option'),
        ),
        migrations.AddField(
            model_name='week',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lms.course'),
        ),
        migrations.AddField(
            model_name='video',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.week'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='CMS.week'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.week'),
        ),
        migrations.AddField(
            model_name='link',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.week'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='CMS.week'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
