# Generated by Django 5.2.7 on 2026-03-06 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
